resources:
- repo: self
phases:
- phase: Build_Mac
  displayName: MacOS

  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  queue:
    name: Hosted macOS
    demands: npm

  steps:
  - task: spontoreau.rust-vsts.rust-install.Rust@1
    displayName: 'Rust Tool Installer'


  - task: spontoreau.rust-vsts.rust-cargo.Cargo@1
    displayName: Cargo
    inputs:
      cargoCommand: build
      cargoCommandOptions: '--release'

  - task: ArchiveFiles@2
    displayName: 'Archive target/release/rust-plantronics'
    inputs:
      rootFolderOrFile: 'target/release/rust-plantronics'
      archiveFile: 'plantronics-darwin-x86_64.zip'

  - task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@1
    displayName: 'Release MacOS'
    inputs:
      githubEndpoint: rob
      githubRepository: 'armyofevilrobots/rust-plantronics'
      githubTag: '$(Build.BuildNumber)'
      githubReleaseTitle: '$(Build.BuildNumber)'
      githubReleaseDraft: false
      githubReleaseAsset: 'plantronics-darwin-x86_64.zip'
      githubReuseDraftOnly: false
